// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZmwuPz_1yuDtWw54kU2ZP-DrbMDI3l0s',
    appId: '1:147717032013:web:9678b5271b27e032ff7404',
    messagingSenderId: '147717032013',
    projectId: 'flutter-firebase-8c02a',
    authDomain: 'flutter-firebase-8c02a.firebaseapp.com',
    storageBucket: 'flutter-firebase-8c02a.appspot.com',
    measurementId: 'G-51XDJRMF44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD2nTfjfyMeCo7orq-AZVz4DuMiSYiKlU',
    appId: '1:147717032013:android:6024fa352438eb59ff7404',
    messagingSenderId: '147717032013',
    projectId: 'flutter-firebase-8c02a',
    storageBucket: 'flutter-firebase-8c02a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhJN8bPhoWH3oynXTM1DcCZiQvF4Ej-g0',
    appId: '1:147717032013:ios:5277c996e5ca047cff7404',
    messagingSenderId: '147717032013',
    projectId: 'flutter-firebase-8c02a',
    storageBucket: 'flutter-firebase-8c02a.appspot.com',
    iosBundleId: 'com.example.flutterCrudOpration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhJN8bPhoWH3oynXTM1DcCZiQvF4Ej-g0',
    appId: '1:147717032013:ios:0fa29a629e978645ff7404',
    messagingSenderId: '147717032013',
    projectId: 'flutter-firebase-8c02a',
    storageBucket: 'flutter-firebase-8c02a.appspot.com',
    iosBundleId: 'com.example.flutterCrudOpration.RunnerTests',
  );
}
